version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/docker/Dockerfile
    ports:
      - '3001:3001'
    env_file: './apps/api-gateway/.env.production'
    networks:
      - internal_network
      - external_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3001/health']
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/docker/Dockerfile
    ports:
      - '3002:3002'
    env_file: './apps/auth-service/.env.production'
    networks:
      - internal_network
      - external_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      auth-db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3002/health']
      interval: 30s
      timeout: 10s
      retries: 3

  auth-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - internal_network
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - internal_network
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth_db_data:
    driver: rexray/ebs
  redis_data:
    driver: rexray/ebs

networks:
  internal_network:
    driver: overlay
    internal: true
  external_network:
    driver: overlay
