FROM node:18-alpine as builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./

RUN npm install -f

COPY . .

EXPOSE 3001

CMD ["npx", "nx", "run", "api-gateway:serve", "--configuration=production"]