FROM node:18-alpine as builder

WORKDIR /app

# Copy only files needed for build
COPY package*.json nx.json tsconfig*.json ./
COPY apps/api-gateway ./apps/api-gateway
COPY libs ./libs

# Install dependencies and build
RUN npm install --force
RUN npx nx build api-gateway --configuration=production --verbose

# Production stage
FROM node:18-alpine

WORKDIR /app

# Copy only production dependencies and built app
COPY --from=builder /app/dist/apps/api-gateway/package*.json ./
RUN npm install --force

COPY --from=builder /app/dist/apps/api-gateway ./

ENV NODE_ENV=production \
    PORT=3001

EXPOSE 3001

CMD ["node", "main.js"]