FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./

RUN npm install -f

COPY . .

CMD ["npx", "nx", "serve", "api-gateway", "--configuration=development", "--watch"]