FROM node:18-alpine as builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./

RUN npm install -f

COPY . .

EXPOSE 3002

CMD ["npx", "nx", "run", "auth-service:serve", "--configuration=production"]