FROM node:18-alpine as builder

WORKDIR /app

# Copy only files needed for build
COPY package*.json nx.json tsconfig*.json ./
COPY apps/auth-service ./apps/auth-service
COPY libs ./libs

# Install dependencies and build
RUN npm install --force
RUN npx nx build auth-service --configuration=production --verbose

# Production stage
FROM node:18-alpine

WORKDIR /app


# Copy only production dependencies and built app
COPY --from=builder /app/dist/apps/auth-service/package*.json ./
RUN npm install --force

COPY --from=builder /app/dist/apps/auth-service ./

ENV NODE_ENV=production \
    PORT=3002

EXPOSE 3002

CMD ["node", "main.js"]