apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - ingress.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - redis.yaml

configMapGenerator:
  - name: app-config
    literals:
      # Redis Configuration
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis-service:6379
      - REDIS_USER=default

      # Service Configuration
      - AUTH_SERVICE_HOST=auth-service-service
      - AUTH_SERVICE_PORT=80

      # Other configurations
      - NODE_ENV=production
      - DB_HOST=postgres-service
      - DB_PORT=5432
      - API_GATEWAY_HOST=api-gateway-service
      - API_GATEWAY_PORT=80

secretGenerator:
  - name: app-secrets
    literals:
      # Redis secrets
      - REDIS_PASSWORD=redis-secret-password
