name: Continuous Deployment

on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed
  pull_request:
    types:
      - closed

jobs:
  docker:
    name: Build and Deploy Changed Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Fetch Doppler Secrets
        run: |
          doppler configure set token ${{ secrets.DOPPLER_TOKEN }}
          doppler secrets --project izistore --config prd --token "${{ secrets.DOPPLER_TOKEN }}" download --format=env --no-file > .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Determine affected projects
        id: affected
        run: |
          BASE_BRANCH=$(git rev-parse --verify main~1 || echo main)
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          AFFECTED=$(npx nx show projects --affected --base=$BASE_BRANCH --head=HEAD)
          if [ -z "$AFFECTED" ]; then
              echo "No affected services. Deploying all services."
              AFFECTED=api-gateway
          fi
          echo "AFFECTED=$AFFECTED" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images using docker-compose
        run: |
          for service in $AFFECTED; do
             docker compose build $service
             docker push ${{ secrets.DOCKER_USERNAME }}/izistore-backend-microservices:$service
           done

  deploy:
    name: Deploy Changed Services
    runs-on: ubuntu-latest
    needs: docker

    steps:
      # 2. Set up SSH Key
      - name: Set up SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

        # 3. SSH into EC2 and Deploy
      - name: Deploy on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

          # Check if EC2_HOST and EC2_USER are correctly set
          echo "EC2 Host: $EC2_HOST"
          echo "EC2 User: $EC2_USER"

          ssh -t -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'

          # Update the system and Docker
          sudo yum update -y


          # Create directory if it doesn't exist
          if [ ! -d "/home/$EC2_USER/izistore-backend-microservices" ]; then
            mkdir -p /home/$EC2_USER/izistore-backend-microservices
          fi


          #Copy Docker Compose from Github
          echo "copy docker compose to server:"
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem

          scp -v -i ec2_key.pem /home/runner/work/izistore-backend/izistore-backend/docker-compose.yml $EC2_USER@$EC2_HOST:/home/$EC2_USER/izistore-backend-microservices/docker-compose.yml

          # Debugging: Log Docker Hub login status on EC2
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker info

          # Pull updated images
          cd /home/$EC2_USER/izistore-backend-microservices
          echo "docker-compose pull command:"
          docker-compose pull
          echo "docker-compose up -d command:"
          docker-compose up -d

          # List images to verify if they exist on the EC2 instance
          docker images
          EOF

      - name: Deployed to server
        run: |
          echo "Done!";
