name: Continuous Deployment

on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: Deploy Changed Services
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }} # Use secrets for sensitive info
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_TARGET_PATH: /home/${{secrets.EC2_USER}}/izistore-backend-microservices
      KUBECONFIG_PATH: /home/${{secrets.EC2_USER}}/.kube/config

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install rsync -y

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Copy Files to EC2
        run: |
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ $EC2_USER@$EC2_HOST:/home/${{secrets.EC2_USER}}/izistore-backend-microservices

      - name: Pull Images from Docker Hub and Deploy to Kind Cluster
        run: |
          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << EOF
            sudo su

            cd ${EC2_TARGET_PATH}

            # Add user to docker group if it doesn't exist and refresh session
            if ! groups $EC2_USER | grep -q docker; then
               sudo usermod -aG docker $EC2_USER
               newgrp docker
            fi

            # Login to Docker Hub (If needed for private images)
            docker login --username "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
            
            npm install -g nx

            npm install

            # Pull and load images to Kind cluster
            images=("api-gateway")

            temp_dir="/tmp/docker-images"
            sudo mkdir -p /tmp/docker-images

            for image in \${images[@]}; do

                if [ -z "\$image" ]; then
                    echo "Skipping empty image name."
                    continue
                fi

                echo "Building image: \$image"
                if ! npx nx run "\$image":build; then
                    echo "Error: Failed to build image \$image"
                    continue
                fi

                echo "Building docker image: $image"
                docker build -t "nebur242/izistore-backend-microservices:\$image"  "dist/apps/\$image"

                echo "Loading image into kind: \$image"
                if ! kind load docker-image "nebur242/izistore-backend-microservices:\$image"; then
                   echo "Error: Failed to load image into kind."
                   continue
                fi

                echo "Image successfully loaded into kind."
            done

            # Set KUBECONFIG
            export KUBECONFIG=${KUBECONFIG_PATH}

            # Apply Kubernetes manifests
            echo "Applying kubernetes manifests"
            sudo kubectl apply -f kubernetes/
            echo "Deployment Complete!"
          EOF
