name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Affected Projects
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootpassword
          POSTGRES_DB: izistore

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Fetch Doppler Secrets
        run: |
          doppler configure set token ${{ secrets.DOPPLER_TOKEN }}
          doppler secrets --project izistore --config prd --token "${{ secrets.DOPPLER_TOKEN }}" download --format=env --no-file > .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Determine affected projects
        id: affected
        run: |
          BASE_BRANCH=$(git rev-parse --verify main~1 || echo main)
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          AFFECTED="api-gateway"
          AFFECTED_TEST=$(npx nx show projects --affected --base=$BASE_BRANCH --head=HEAD)
          echo $AFFECTED_TEST
          # AFFECTED=$(npx nx show projects --affected --base=$BASE_BRANCH --head=HEAD)
          # if [ -z "$AFFECTED" ]; then
          #   echo "No affected services. Deploying all services."
          #   AFFECTED="api-gateway user-service product-service order-service"
          # fi
          # echo "AFFECTED=$AFFECTED"
          # echo "AFFECTED=$AFFECTED" >> $GITHUB_ENV

      - name: Build affected projects
        run: npx nx affected --target=build --base=$BASE_BRANCH --head=HEAD

      - name: Run tests for affected projects
        run: npx nx affected --target=test --base=$BASE_BRANCH --head=HEAD

      - name: Run linting for affected projects
        run: npx nx affected --target=lint --base=$BASE_BRANCH --head=HEAD

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images using docker-compose
        run: |
          for service in $AFFECTED; do
            echo "Building service $service..."
            docker build -t ${{ secrets.DOCKER_USERNAME }}/izistore-backend-microservices:$service dist/apps/$service
            echo "Pushing service $service to dockerhub..."
            docker push ${{ secrets.DOCKER_USERNAME }}/izistore-backend-microservices:$service
            echo "Done successfully..."
          done
